### PR TITLE
Fix file truncation on Windows with bash

### LINKED ISSUE #1494: File not overwritten by >file under Cygwin
I use Cygwin on windows, tjek this:

```
$ printf "A\nB\n">t

$ cat t
A
B

$ printf "Z\n">t

$ cat t
Z
B
```

### PR DESCRIPTION
**Pull request by taruti**
When a file is opened with FILE_OPEN_IF with Dokan and the file
exists it should be returned, but additionally ErrObjectNameCollision
should be returned.

Fixes KBFS-2812 and Fixes #1494

This ended up requiring quite a lot of restructuring code since
we need to pass up whether a file was created or an existing
one is returned. Doing this on all the return sites would have
been even more messy.

### CODE REVIEW

File: libdokan/tlf.go [hunk 1]
```diff
@@ -157,13 +157,14 @@ func (tlf *TLF) GetFileInformation(ctx context.Context, fi *dokan.FileInfo) (st
 }
 
 // open tries to open a file.
-func (tlf *TLF) open(ctx context.Context, oc *openContext, path []string) (dokan.File, bool, error) {
+func (tlf *TLF) open(ctx context.Context, oc *openContext, path []string) (
+	dokan.File, dokan.CreateStatus, error) {
 	if len(path) == 0 {
 		if err := oc.ReturningDirAllowed(); err != nil {
-			return nil, true, err
+			return nil, 0, err
```
Comment (jzila) [inline libdokan/tlf.go]: Is this behavior correct? It used to return `true`, which should map to `dokan.ExistingDir`. Was that previously a bug?

File: dokan/filesystem.go [hunk 2]
```diff
@@ -54,6 +54,34 @@ type FileSystem interface {
 	ErrorPrint(error)
 }
 
+// CreateStatus marks status of successfull create/open operations.
+type CreateStatus uint32
+
+const (
+	// 1 Bit 0 == always set for valid values,
```
[the remark this answers is not in the document]
Comment (taruti) [reply dokan/filesystem.go]: Will use constants.

File: libdokan/tlf.go (hunk 1 above)
Comment (taruti) [reply libdokan/tlf.go]: Here CreateFile fails so the CreateStatus is ignored.

**Comment by taruti** [comment]
Addressed review, rebased to master for CI-passing and handle also FileSupersede and FileOverwriteIf similarly.

File: libdokan/tlf.go (hunk 1 above)
Comment (jzila) [reply libdokan/tlf.go]: SGTM
